# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_scraper', '0017_added_order_to_scraped_obj_attr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(help_text="Two-letter country code (e.g. 'BE', 'CZ', 'PL')", max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('agency_name', models.CharField(max_length=200)),
                ('info_url', models.URLField()),
                ('data_url', models.URLField()),
                ('nc_symbol', models.CharField(blank=True, help_text="Symbol of the national currency (e.g. 'GBP'), only enter for non \u20ac countries", max_length=3)),
                ('nc_sign', models.CharField(blank=True, help_text="Sign of the national currency (e.g. '\xa3'), only enter for non \u20ac countries", max_length=6)),
                ('scrape_url', models.URLField()),
                ('comments', models.TextField(blank=True)),
                ('scraper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.Scraper')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(help_text="Two-letter country code (e.g. 'BE', 'CZ', 'PL')", max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
                ('town', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField()),
                ('amount_nc', models.FloatField(blank=True, null=True)),
                ('nc_conv_date', models.DateTimeField(blank=True, null=True)),
                ('nc_conv_rate', models.FloatField(blank=True, null=True)),
                ('sub_payments_nc', models.TextField(blank=True)),
                ('sub_payments_euro', models.TextField(blank=True)),
                ('amount_euro', models.FloatField()),
            ],
        ),
    ]
