# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='payment',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
