# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_data', '0002_added_name_en_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language_code',
            field=models.CharField(default='en', help_text="Two-letter country code, lower-case (e.g. 'en', 'cs', 'bg')", max_length=2),
            preserve_default=False,
        ),
    ]
