# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_data', '0003_added_language_code_for_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
